### ISSUE TITLE
Default login doe not work

### ISSUE THREAD

**Issue by guysoft** [guysoft/LibrePhotosOS#1]
Default login doe not work.
I have set it to be admin/admin, but it does not work.

Setting done here:
https://github.com/guysoft/LibrePhotosOS/blob/devel/src/modules/librephotosos/filesystem/boot/docker-compose/librephotos/.env#L75

**Comment by derneuere** [comment]
I pushed a new release: https://old.reddit.com/r/librephotos/comments/tqehwr/librephotos_development_2022_week_13/
We now have a first time setup, which means userName and userPass are no longer needed.
