### ISSUE TITLE
Default secret should be generated on first boot

### ISSUE THREAD

**Issue by guysoft** [guysoft/LibrePhotosOS#2]
A script should run before the docker-compose service, and generate the secret.

The secret is currently hardcoded at:
https://github.com/guysoft/LibrePhotosOS/blob/devel/src/modules/librephotosos/filesystem/boot/docker-compose/librephotos/.env#L23

**Comment by derneuere** [comment]
You can now remove shhhKey. On startup, it will generate a new secret.key in the log folder, if he can't find it.
