### ISSUE TITLE
Create new image on new release

### ISSUE THREAD

**Issue by derneuere** [guysoft/LibrePhotosOS#4]
We currently release a new version around every week. You can find the releases here: https://github.com/LibrePhotos/librephotos-docker/releases

It would be great, if there could be an automated job, which checks if there is a new update and the builds a new image for the raspberry.

**Comment by guysoft** [comment]
Thr image automatically updates. See #5
It does not ship with the image. It pulles it at first boot

**Comment by derneuere** [comment]
Thanks for the clarification!
